// Add a verified public URL to any project to display its Visit website link.
export const projects = [
{id:'glams',name:'GLAMS',label:'LEARNING, WITH A PLAYFUL SIDE',category:'learning',color:'cobalt',short:'Gamified learning & assessment',description:'A learning platform that brings progress, participation, and friendly competition together.',tags:['React.js','Node.js','MySQL','MongoDB'],url:'https://glams.cpatverse.in',details:['Built modules for leaderboards, user profiles, star ratings, and administration.','Enhanced the interface with Particle.js and used Docker and Git for delivery.','Performed functional testing and represented the project at the GPAI summit.']},
{id:'manufacturing',name:'Manufacturing Unit Monitoring',label:'A CLEARER VIEW OF OPERATIONS',category:'systems',color:'tangerine',short:'Monitoring manufacturing operations',description:'A monitoring system for tracking manufacturing data and understanding operational performance.',tags:['Java','Spring Boot','Data analysis'],url:'',details:['Developed a Spring Boot-based monitoring system for manufacturing operations.','Implemented real-time data tracking and analysis features.','Designed a scalable backend with performance metrics.']},
{id:'learndex',name:'LearnDex',label:'CONNECTING THE LEARNING EXPERIENCE',category:'learning',color:'mint',short:'Courses, credits & reviews',description:'Connected course management, user reviews, and credit management in a responsive learning experience.',tags:['React.js','HTML','Bootstrap'],url:'',details:['Integrated frontend and backend components for user reviews, credit management, and course management.','Built responsive interfaces using React.js, HTML, and Bootstrap.','Performed functional testing. Project period: June–August 2023.']},
{id:'library',name:'Library Management System',label:'LESS ADMIN. MORE DISCOVERY.',category:'systems',color:'lilac',short:'Books, members & borrowing',description:'A Java application that helps organize book catalogs, manage members, and track lending.',tags:['Java','Database operations','OOP'],url:'',details:['Developed book cataloging, user management, and lending tracking.','Implemented database operations and an intuitive interface.','Used object-oriented design and Eclipse IDE. Project period: December 2022–January 2023.']}
];


