'use client';
import {useState,useRef,useEffect} from 'react';
import {Code2,Layers,Database,Terminal,Mail,Copy,Check,Plus,X,BookOpen,Trophy,Activity,GraduationCap,Menu,MousePointer2,Command} from 'lucide-react';
import {projects} from '../lib/projects';
import WebsiteCollection from './website-collection';

const stack={Frontend:{icon:Code2,items:['React.js','JavaScript','HTML & CSS','Bootstrap'],note:'The part you see. Interfaces that feel clear, responsive, and easy to use.'},Backend:{icon:Terminal,items:['Java','Spring Boot','Node.js','Express.js'],note:'The logic underneath. APIs and services that turn an interface into a working product.'},Data:{icon:Database,items:['MySQL','MongoDB','PostgreSQL','Docker & Git'],note:'The foundation. Structured data, reliable storage, and a repeatable delivery process.'}};
function ProjectVisual({id}){return <div className={'visual '+id} aria-label="Illustrative project concept, not a live application screenshot"><div className="concept-label"><span>INTERFACE CONCEPT</span><span>AP / {id.toUpperCase()}</span></div>{id==='glams'?<div className="mini-window"><div className="mini-toolbar"><span className="mini-logo">g.</span><b>Make progress. Have fun.</b><Trophy size={17}/></div><div className="learning-body"><div><small>YOUR NEXT CHAPTER</small><h4>A little better,<br/>every day.</h4><div className="progress-track"><i/></div><span className="mini-muted">Learn · Practice · Level up</span></div><div className="score-orbit"><Trophy size={35}/><span>Keep growing</span></div></div><div className="mini-pills"><span>Learning paths</span><span>Leaderboard</span><span>Achievements</span></div></div>:id==='manufacturing'?<div className="monitor-window"><div className="monitor-header"><Activity size={19}/><b>Operations overview</b><span>ILLUSTRATIVE</span></div><div className="monitor-chart">{[30,48,40,70,57,80,68,92,79,97,83,100].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><div className="monitor-footer"><span>TRACK</span><span>ANALYZE</span><span>UNDERSTAND</span></div></div>:id==='learndex'?<div className="course-window"><div className="course-title"><BookOpen size={22}/><b>LearnDex</b><span>Your learning shelf</span></div><div className="course-tiles"><div><Code2/><span>Explore<br/><b>new skills.</b></span></div><div><Layers/><span>Build<br/><b>your next chapter.</b></span></div></div></div>:<div className="library-window"><div><BookOpen size={30}/><h4>A place for<br/>every story.</h4><span>Catalog. Borrow. Discover.</span></div><div className="catalog-list">{['The catalog','Your members','On the shelves'].map((t,i)=><div key={t}><span>0{i+1}</span><b>{t}</b><Plus size={14}/></div>)}</div></div>}</div>}
export default function Home(){const [filter,setFilter]=useState('all');const [activeStack,setActiveStack]=useState('Frontend');const [project,setProject]=useState(null);const [copied,setCopied]=useState(false);const [menu,setMenu]=useState(false);const [accent,setAccent]=useState('blue');const dialog=useRef(null);const lastFocus=useRef(null);const Icon=stack[activeStack].icon;
useEffect(()=>{if(project)dialog.current?.showModal()},[project]);
function close(){dialog.current?.close();setProject(null);lastFocus.current?.focus()}
async function copy(){try{await navigator.clipboard.writeText('aniketpattiwar@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{setCopied(false)}}
return <div className={'site accent-'+accent}>
<a className="skip" href="#main">Skip to content</a>
<header className="nav-shell"><a className="wordmark" href="#home">aniket<span>®</span><small>DEVELOPER & BUILDER</small></a><button className="mobile-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''} aria-label="Main navigation">{[['Websites','websites'],['Work','work'],['About','about']].map(([name,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{name}</a>)}<a href="#contact" className="nav-hello" onClick={()=>setMenu(false)}>Let’s talk <Mail size={15}/></a></nav></header>
<main id="main"><section className="hero container" id="home"><div className="hero-topline"><span>Hi, I’m Aniket Pattiwar.</span><span>Full stack developer · Patna, India</span></div><div className="hero-heading"><h1>I like making<br/><em>useful things</em><br/>for the web<span className="period">.</span></h1><div className="hero-note"><span className="hero-index">A small collection<br/>of things I’ve built.</span><p>Learning resources, little tools, and full stack applications. This is where they all come together.</p><a href="#websites" className="round-link">Explore my websites <MousePointer2 size={18}/></a><a className="hero-secondary" href="#about">Meet the person behind them</a></div></div><div className="hero-bottom"><p>REACT / JAVA / NODE.JS / A BIT OF CURIOSITY</p><div className="color-picker"><span>PICK YOUR COLOR</span>{['blue','orange','green'].map(c=><button key={c} className={'swatch '+c} aria-label={'Use '+c+' accent'} aria-pressed={accent===c} onClick={()=>setAccent(c)}>{accent===c&&<Check size={13}/>}</button>)}</div></div></section><WebsiteCollection/>
<section className="intro-bento container"><div className="identity-tile"><div className="tile-top"><Code2 size={23}/><span>A LITTLE ABOUT ME</span></div><h2>Aniket<br/>Pattiwar<span>_</span></h2><div className="identity-foot"><span>Building with intention.<br/>Learning along the way.</span><span className="monogram">ap.</span></div></div><div className="stack-tile" id="toolkit"><div className="tile-top"><span>HOW I BUILD</span><Command size={18}/></div><div className="stack-tabs" role="tablist" aria-label="Technology areas">{Object.keys(stack).map(s=><button role="tab" id={'tab-'+s} aria-controls="stack-panel" aria-selected={s===activeStack} key={s} onClick={()=>setActiveStack(s)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const keys=Object.keys(stack);const next=keys[(keys.indexOf(s)+(e.key==='ArrowRight'?1:2))%3];setActiveStack(next);document.getElementById('tab-'+next)?.focus()}}}>{s}</button>)}</div><div id="stack-panel" role="tabpanel" aria-labelledby={'tab-'+activeStack} className="stack-content" key={activeStack}><Icon size={30}/><h3>{stack[activeStack].items.join(' / ')}</h3><p>{stack[activeStack].note}</p></div></div><a className="resume-tile" href="/Aniket_Resume.pdf" target="_blank" rel="noopener"><span>MY RESUME</span><div className="resume-symbol"><Layers size={56} strokeWidth={1}/></div><div><h3>Experience,<br/>on paper.</h3><span className="resume-link">Read my resume <Plus size={18}/></span></div></a></section>
<section className="work container" id="work"><div className="section-caption"><span>WORK EXPERIENCE</span><span>PROFESSIONAL PROJECTS</span></div><div className="work-heading"><h2>On the job,<br/><em>behind the scenes.</em></h2><p>Learning platforms, connected systems,<br/>and the details that make them work.</p></div><div className="filter-row"><div className="filters" role="group" aria-label="Project categories">{[['all','All work','04'],['learning','Learning','02'],['systems','Systems','02']].map(([id,name,count])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)} className={filter===id?'active':''}>{name}<sup>{count}</sup></button>)}</div><span className="collection-label">A GROWING COLLECTION</span></div><div className="project-grid">{projects.filter(p=>filter==='all'||p.category===filter).map((p)=><article className="project-card" key={p.id}><button className="project-cover" aria-label={'Explore '+p.name} onClick={e=>{lastFocus.current=e.currentTarget;setProject(p)}}><ProjectVisual id={p.id}/><span className="open-project"><Plus size={21}/></span></button><div className="project-info"><div><p className="project-category">{p.category==='learning'?'LEARNING & COMMUNITY':'SYSTEMS & OPERATIONS'} <span>/ 0{projects.indexOf(p)+1}</span></p><h3><button onClick={e=>{lastFocus.current=e.currentTarget;setProject(p)}}>{p.name}</button></h3><p>{p.description}</p></div><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div>{p.url&&/^https?:\/\//.test(p.url)&&<a href={p.url} target="_blank" rel="noopener noreferrer" className="live-link">{p.id === 'glams' ? 'View' : 'Visit website'}</a>}</div></article>)}</div></section>
<section className="about-section" id="about"><div className="container"><div className="section-caption"><span>ABOUT ME</span><span>A LITTLE BACKSTORY</span></div><div className="about-grid"><div className="about-title"><span className="asterisk" aria-hidden="true">✳</span><h2>I care about<br/>how it works.<br/><em>And how it feels.</em></h2><p>About the people using it.<br/>About the small details.<br/>About what happens after it ships.</p></div><div className="about-content"><p className="lead">I’m Aniket, a full stack developer who enjoys making all the pieces fit.</p><p>My work at C-DAC spans gamified learning, manufacturing monitoring, course management, and library systems. I’m interested in the whole journey — from how a screen feels to how its data moves.</p><p>I work with React and JavaScript on the frontend, Java and Node.js on the backend, and the databases and tools that bring everything together.</p><div className="milestone"><Trophy size={25}/><div><small>A MOMENT I’M PROUD OF</small><h3>Taking GLAMS to the GPAI summit.</h3><p>Represented the project at the Global Partnership on AI summit and contributed to its beta deployment.</p></div></div></div></div><div className="timeline"><article><span>01 / EXPERIENCE</span><h3>Project Engineer</h3><p>C-DAC, Patna</p><small>Dec 2022 – Present, as listed in resume</small></article><article><span>02 / SPECIALIZATION</span><h3>Advanced Computing</h3><p>PG-DAC · C-DAC, Mumbai</p><small>March – September 2022 · 73%</small></article><article><span>03 / FOUNDATION</span><h3>Bachelor of Engineering</h3><p>Sant Gadge Baba Amravati University</p><small>2015 – 2019 · CGPA 7.4/10</small></article></div></div></section>
<section className="contact container" id="contact"><div className="section-caption"><span>GET IN TOUCH</span><Mail size={22}/></div><h2>Something in mind?<br/><a href="mailto:aniketpattiwar@gmail.com">Let’s make it <em>happen.</em></a></h2><div className="contact-bottom"><p>A project, an opportunity, or a conversation.<br/>I’d love to hear what you’re thinking.</p><div><a href="mailto:aniketpattiwar@gmail.com" className="email">aniketpattiwar@gmail.com</a><button onClick={copy} className="copy" aria-label="Copy email address">{copied?<Check size={19}/>:<Copy size={19}/>}</button><span className="copy-message" role="status">{copied?'Copied!':''}</span></div></div></section>
</main><footer className="container"><a href="#home" className="footer-logo">ap.</a><p>Thoughtfully built. Always evolving.</p><a href="#home">Back to the top</a><span>© {new Date().getFullYear()} ANIKET PATTIWAR</span></footer>
<dialog ref={dialog} className="project-dialog" onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===dialog.current){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}}} aria-labelledby="dialog-title">{project&&<><div className="dialog-head"><span>BEHIND THE PROJECT / 0{projects.indexOf(project)+1}</span><button onClick={close} aria-label="Close project"><X/></button></div><ProjectVisual id={project.id}/><div className="dialog-body"><h2 id="dialog-title">{project.name}</h2><p>{project.description}</p><h3>My contribution</h3><ul>{project.details.map(d=><li key={d}>{d}</li>)}</ul><div className="tags">{project.tags.map(t=><span key={t}>{t}</span>)}</div><p className="public-note">{project.url?<a href={project.url} target="_blank" rel="noopener noreferrer">{project.id === 'glams' ? 'View' : 'Visit website'}</a>:'Project overview · Public link not available yet'}</p></div></>}</dialog>
</div>}


